-- Seed: 128 jogos importados da planilha original
-- Gerado automaticamente

TRUNCATE TABLE jogos RESTART IDENTITY CASCADE;

INSERT INTO jogos (
    data, dia_semana, time_casa, time_visitante, is_corinthians, mando,
    campeonato, genero, estadio, status_presenca, setor, assento,
    valor_pago, gols_casa, gols_visitante, resultado, foi_classico, teve_penal
) VALUES
    ('2013-08-11', 'Domingo', 'Corinthians', 'Vitória', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Pacaembú', 'PRESENTE', 'Arquibancada Laranja', NULL, NULL, 2, 0, 'V', FALSE, FALSE),
    ('2015-12-06', 'Domingo', 'Corinthians', 'Avaí', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', NULL, NULL, 1, 1, 'E', FALSE, FALSE),
    ('2016-04-16', 'Sábado', 'Corinthians', 'RB Brasil', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', NULL, NULL, 4, 0, 'V', FALSE, FALSE),
    ('2016-07-03', 'Domingo', 'Corinthians', 'Flamengo', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', NULL, NULL, 4, 0, 'V', TRUE, FALSE),
    ('2017-05-13', 'Sábado', 'Corinthians', 'Chapecoense', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', NULL, NULL, 1, 1, 'E', FALSE, FALSE),
    ('2017-08-05', 'Sábado', 'Corinthians', 'Sport', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', NULL, NULL, 3, 1, 'V', FALSE, FALSE),
    ('2017-11-15', 'Quarta', 'Corinthians', 'Fluminense', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', NULL, NULL, 3, 1, 'V', FALSE, FALSE),
    ('2018-01-17', 'Quarta', 'Corinthians', 'Ponte Preta', TRUE, 'MANDANTE', 'Paulista', 'M', 'Pacaembú', 'PRESENTE', 'Arquibancada Coberta', NULL, NULL, 0, 1, 'D', FALSE, FALSE),
    ('2018-01-24', 'Quarta', 'Corinthians', 'Ferroviária', TRUE, 'MANDANTE', 'Paulista', 'M', 'Pacaembú', 'PRESENTE', 'Tobogã', NULL, NULL, 2, 1, 'V', FALSE, FALSE),
    ('2018-03-18', 'Domingo', 'Corinthians', 'Bragantino', TRUE, 'MANDANTE', 'Paulista', 'M', 'Pacaembú', 'PRESENTE', 'Arquibancada Coberta', NULL, NULL, 2, 3, 'D', FALSE, FALSE),
    ('2018-03-28', 'Quarta', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', NULL, NULL, 1, 0, 'V', TRUE, TRUE),
    ('2019-01-13', 'Domingo', 'Corinthians', 'Santos', TRUE, 'MANDANTE', 'Amistoso', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[424] AA-25 [H]', 40.0, 1, 1, 'E', TRUE, FALSE),
    ('2019-02-17', 'Domingo', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Sul', '[417] GG-4 [E]', 80.0, 2, 1, 'V', TRUE, FALSE),
    ('2019-02-17', 'Domingo', 'Corinthians', 'Oeste', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', '[402] L-2 [A]', 67.5, 1, 0, 'V', FALSE, FALSE),
    ('2019-03-10', 'Domingo', 'Corinthians', 'Santos', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[426] A-47 [N]', 67.5, 0, 0, 'E', TRUE, FALSE),
    ('2019-03-31', 'Domingo', 'Corinthians', 'Santos', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] AA-25 [N]', 90.0, 2, 1, 'V', TRUE, FALSE),
    ('2019-04-21', 'Domingo', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] Q-20 [N]', 150.0, 2, 1, 'V', TRUE, FALSE),
    ('2019-05-01', 'Quarta', 'Corinthians', 'Chapecoense', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', '[402] O-2 [A]', 55.0, 2, 0, 'V', FALSE, FALSE),
    ('2019-05-11', 'Sábado', 'Corinthians', 'Grêmio', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] O-13 [N]', 52.5, 0, 0, 'E', FALSE, FALSE),
    ('2019-05-25', 'Sábado', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] O-25 [N]', 67.5, 1, 0, 'V', TRUE, FALSE),
    ('2019-07-14', 'Domingo', 'Corinthians', 'CSA', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Sul', '[412] D-9 [E]', 34.5, 1, 0, 'V', FALSE, FALSE),
    ('2019-09-08', 'Domingo', 'Corinthians', 'Ceará', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[426] U-6 [N]', NULL, 2, 2, 'E', FALSE, FALSE),
    ('2019-11-16', 'Sábado', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Paulista', 'F', 'Neo Química Arena', 'PRESENTE', 'Norte', NULL, NULL, 3, 0, 'V', TRUE, FALSE),
    ('2020-02-02', 'Domingo', 'Corinthians', 'Santos', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', '[402] J-2 [A]', 142.5, 2, 0, 'V', FALSE, FALSE),
    ('2020-02-12', 'Quarta', 'Corinthians', 'Guarani (PAR)', TRUE, 'MANDANTE', 'Libertadores', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] AA-3 [N]', 65.8, 2, 1, 'V', FALSE, FALSE),
    ('2021-10-05', 'Terça', 'Corinthians', 'Bahia', TRUE, 'MANDANTE', NULL, 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] A-13 [N]', 56.0, 3, 1, 'V', FALSE, FALSE),
    ('2021-10-13', 'Quarta', 'Corinthians', 'Fluminense', TRUE, 'MANDANTE', NULL, 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] K-11 [N]', 56.0, 1, 0, 'V', FALSE, FALSE),
    ('2021-11-01', 'Segunda', 'Corinthians', 'Chapecoense', TRUE, 'MANDANTE', NULL, 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] R-21 [N]', 56.0, 1, 0, 'V', FALSE, FALSE),
    ('2021-11-06', 'Sábado', 'Corinthians', 'Fortaleza', TRUE, 'MANDANTE', NULL, 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] U-20 [N]', 56.0, 1, 0, 'V', FALSE, FALSE),
    ('2021-11-13', 'Sábado', 'Corinthians', 'Cuiabá', TRUE, 'MANDANTE', NULL, 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] U-20 [N]', 56.0, 3, 2, 'V', FALSE, FALSE),
    ('2021-11-21', 'Domingo', 'Corinthians', 'Santos', TRUE, 'MANDANTE', NULL, 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] U-17 [N]', 56.0, 2, 0, 'V', TRUE, FALSE),
    ('2021-12-01', 'Quarta', 'PSG', 'Nice', FALSE, 'NEUTRO', NULL, 'M', 'Parc des Princes', 'PRESENTE', NULL, '[108] L-26 [F]', NULL, NULL, NULL, NULL, FALSE, FALSE),
    ('2022-01-25', 'Terça', 'Corinthians', 'Ferroviária', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[418] P-4 [H]', 49.9, 0, 0, 'E', FALSE, FALSE),
    ('2022-01-30', 'Domingo', 'Santo André', 'Corinthians', TRUE, 'VISITANTE', 'Paulista', 'M', 'Bruno José Daniel', 'PRESENTE', 'Oeste', '[B] Visitante', 52.1, 1, 0, 'V', FALSE, FALSE),
    ('2022-02-02', 'Quarta', 'Corinthians', 'Santos', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] I-13 [H]', 78.0, 1, 2, 'D', TRUE, FALSE),
    ('2022-02-06', 'Domingo', 'Corinthians', 'Palmeiras', TRUE, 'MANDANTE', NULL, 'F', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', '[402] P-8 [A]', 30.0, 3, 0, 'V', FALSE, FALSE),
    ('2022-02-10', 'Quinta', 'Corinthians', 'Mirassol', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Superior', '[622] D-13 [J]', 48.0, 3, 0, 'V', FALSE, FALSE),
    ('2022-02-27', 'Domingo', 'Corinthians', 'Bragantino', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] Y-14 [H]', 66.0, 1, 0, 'V', FALSE, FALSE),
    ('2022-03-24', 'Quinta', 'Corinthians', 'Guarani', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] S-18 [N]', 60.0, 1, 1, 'E', FALSE, TRUE),
    ('2022-04-13', 'Quarta', 'Corinthians', 'Deportivo Cali', TRUE, 'MANDANTE', 'Libertadores', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] N-12 [H]', 112.5, 1, 0, 'V', FALSE, FALSE),
    ('2022-04-26', 'Terça', 'Corinthians', 'Boca Juniors', TRUE, 'MANDANTE', 'Libertadores', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] R-12 [N]', 97.5, 2, 0, 'V', TRUE, FALSE),
    ('2022-05-01', 'Domingo', 'Corinthians', 'Fortaleza', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] Z-13 [N]', 71.5, 1, 0, 'V', FALSE, FALSE),
    ('2022-05-11', 'Quarta', 'Corinthians', 'Portuguesa-RJ', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] 0-12 [H]', 72.0, 2, 0, 'V', FALSE, FALSE),
    ('2022-05-22', 'Domingo', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', '[403] W-14 [A]', 160.0, 1, 1, 'E', TRUE, FALSE),
    ('2022-05-29', 'Domingo', 'Corinthians', 'América-MG', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] T-16 [H]', 82.0, 1, 1, 'E', FALSE, FALSE),
    ('2022-06-22', 'Quarta', 'Corinthians', 'Santos', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] X-19 [H]', 75.0, 4, 0, 'V', TRUE, FALSE),
    ('2022-06-28', 'Terça', 'Corinthians', 'Boca Juniors', TRUE, 'MANDANTE', 'Libertadores', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] N-13 [H]', 123.75, 0, 0, 'E', TRUE, FALSE),
    ('2022-07-10', 'Domingo', 'Corinthians', 'Flamengo', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Business', '[805] D-8 [B]', 375.0, 1, 0, 'V', TRUE, FALSE),
    ('2022-07-20', 'Quarta', 'Corinthians', 'Coritiba', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Superior', '[622] D-14 [J]', 55.0, 3, 1, 'V', FALSE, FALSE),
    ('2022-07-30', 'Sábado', 'Corinthians', 'Botafogo', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] U-17 [H]', 65.0, 1, 0, 'V', FALSE, FALSE),
    ('2022-08-02', 'Terça', 'Corinthians', 'Flamengo', TRUE, 'MANDANTE', 'Libertadores', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] U-12 [N]', 154.0, 0, 2, 'D', FALSE, FALSE),
    ('2022-08-13', 'Sábado', 'Corinthians', 'Palmeiras', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] R-19 [N]', 84.5, 0, 1, 'D', TRUE, FALSE),
    ('2022-08-17', 'Quarta', 'Corinthians', 'Atlético-GO', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] S-18 [N]', 65.0, 4, 1, 'V', FALSE, FALSE),
    ('2022-08-29', 'Segunda', 'Corinthians', 'Bragantino', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'AUSENTE', 'Leste Superior', '[622] B-8 [J]', 55.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2022-09-04', 'Domingo', 'Corinthians', 'Internacional', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'AUSENTE', 'Leste Inferior', '[422] D-19 [H]', 75.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2022-09-11', 'Domingo', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Morumbi', 'PRESENTE', 'Oeste', 'Morumbi', 100.0, 1, 1, 'E', TRUE, FALSE),
    ('2022-09-15', 'Quinta', 'Corinthians', 'Fluminense', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] W-17 [N]', 40.0, 3, 0, 'V', FALSE, FALSE),
    ('2022-09-24', 'Sábado', 'Corinthians', 'Internacional', TRUE, 'MANDANTE', NULL, 'F', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', NULL, NULL, 4, 1, 'V', FALSE, FALSE),
    ('2022-10-08', 'Sábado', 'Corinthians', 'Atlético-PR', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'AUSENTE', 'Leste Inferior', '[425] Y-22 [N]', 40.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2022-10-12', 'Quarta', 'Corinthians', 'Flamengo', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] V-22 [N]', 40.0, 0, 0, 'E', TRUE, FALSE),
    ('2022-10-19', 'Quarta', 'Flamengo', 'Corinthians', TRUE, 'VISITANTE', 'Copa do Brasil', 'M', 'Maracanã', 'PRESENTE', 'Visitante', 'Maracanã-RJ', 0.0, 1, 1, 'E', TRUE, TRUE),
    ('2022-10-26', 'Quarta', 'Corinthians', 'Fluminense', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] V-22 [N]', 40.0, 0, 2, 'D', FALSE, FALSE),
    ('2022-11-13', 'Domingo', 'Corinthians', 'Atlético-MG', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'AUSENTE', 'Leste Inferior', '[418] K-14 [H]', 35.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2023-01-18', 'Quarta', 'Corinthians', 'Água Santa', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Superior', '[622] D-15 [J]', 54.0, 3, 0, 'V', FALSE, FALSE),
    ('2023-01-24', 'Terça', 'Corinthians', 'Guarani', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Superior', '[622] F-13 [J]', 49.5, 2, 1, 'V', FALSE, FALSE),
    ('2023-02-05', 'Domingo', 'Corinthians', 'Botafogo-SP', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'AUSENTE', 'Leste Inferior', '[425] DD-21 [N]', 55.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2023-02-16', 'Quinta', 'Corinthians', 'Palmeiras', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] N-20 [N]', 55.0, 2, 2, 'E', TRUE, FALSE),
    ('2023-03-12', 'Domingo', 'Corinthians', 'Ituano', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Superior', NULL, 82.5, 1, 1, 'E', FALSE, TRUE),
    ('2023-04-17', 'Segunda', 'Corinthians', 'Palmeiras', TRUE, 'MANDANTE', NULL, 'F', 'Fazendinha', 'PRESENTE', 'Arquibancada', NULL, 0.0, 3, 2, 'V', TRUE, FALSE),
    ('2023-05-02', 'Terça', 'Corinthians', 'Remo', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', '[408] O-21 [A]', 132.0, 2, 0, 'V', FALSE, TRUE),
    ('2023-05-02', 'Terça', 'Corinthians', 'Ind. Del Valle', TRUE, 'MANDANTE', 'Libertadores', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] L-11 [H]', 82.8, 0, 2, 'D', FALSE, FALSE),
    ('2023-05-31', 'Quarta', 'Corinthians', 'Atlético-MG', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] Z-19 [N]', 115.0, 2, 0, 'V', FALSE, TRUE),
    ('2023-06-28', 'Quarta', 'Corinthians', 'Liverpool URU', TRUE, 'MANDANTE', 'Libertadores', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Superior', '[911] Q-5 [B]', NULL, 4, 0, 'V', FALSE, FALSE),
    ('2023-07-11', 'Terça', 'Corinthians', 'Universitário', TRUE, 'MANDANTE', 'Sulamericana', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] U-21 [N]', 37.5, 1, 0, 'V', FALSE, FALSE),
    ('2023-07-15', 'Sábado', 'Corinthians', 'América-MG', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] S-20 [N]', 66.0, 3, 2, 'V', FALSE, FALSE),
    ('2023-09-26', 'Terça', 'Corinthians', 'Fortaleza', TRUE, 'MANDANTE', 'Sulamericana', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] [N]', 99.0, 1, 1, 'E', FALSE, FALSE),
    ('2023-10-07', 'Sábado', 'Corinthians', 'Flamengo', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', NULL, 74.0, 1, 1, 'E', TRUE, FALSE),
    ('2023-10-29', 'Domingo', 'Corinthians', 'Santos', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', NULL, 74.0, 1, 1, 'E', TRUE, FALSE),
    ('2024-01-21', 'Domingo', 'Corinthians', 'Guarani', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] J-24 [N]', 65.0, 1, 0, 'V', FALSE, FALSE),
    ('2024-01-25', 'Quinta', 'Corinthians', 'Cruzeiro', TRUE, 'MANDANTE', 'Copinha', 'S-20', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] R-22 [N]', 28.0, 1, 0, 'V', FALSE, FALSE),
    ('2024-01-30', 'Terça', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] R-23 [N]', 75.0, 2, 1, 'D', TRUE, FALSE),
    ('2024-02-04', 'Domingo', 'Corinthians', 'Novorizontino', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Superior', '[623] Q-12 [L]', 58.5, 1, 3, 'D', FALSE, FALSE),
    ('2024-04-09', 'Terça', 'Corinthians', 'Nacional URU', TRUE, 'MANDANTE', 'Sulamericana', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Superior', '[623] AA-15 [L]', 75.0, 4, 0, 'V', FALSE, FALSE),
    ('2024-04-14', 'Domingo', 'Corinthians', 'Atlético-MG', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] R-23 [N]', 75.0, 0, 0, 'E', FALSE, FALSE),
    ('2024-05-04', 'Sábado', 'Corinthians', 'Fortaleza', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Inferior', '[403] A-12 [D]', 120.0, 0, 0, 'E', FALSE, FALSE),
    ('2024-06-26', 'Quarta', 'Corinthians', 'Cuiabá', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[419] CC-7 [H]', 75.0, 1, 1, 'E', FALSE, FALSE),
    ('2024-07-04', 'Quinta', 'Corinthians', 'Vitória', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[426] W-45 [N]', 75.0, 3, 2, 'V', FALSE, FALSE),
    ('2024-07-16', 'Terça', 'Corinthians', 'Criciúma', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] L-11 [N]', 75.0, 2, 1, 'V', FALSE, FALSE),
    ('2024-07-31', 'Quarta', 'Corinthians', 'Grêmio', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[418] JJ-39 [H]', 75.0, 0, 0, 'E', FALSE, FALSE),
    ('2024-08-04', 'Domingo', 'Corinthians', 'Juventude', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] Y-16 [N]', 75.0, 0, 0, 'E', FALSE, FALSE),
    ('2024-09-21', 'Sábado', 'Corinthians', 'Atlético-GO', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[424] V-17 [N]', 112.5, 3, 0, 'V', FALSE, FALSE),
    ('2024-10-20', 'Domingo', 'Corinthians', 'Flamengo', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[424] W-9 [N]', 112.5, 0, 0, 'E', FALSE, FALSE),
    ('2024-10-24', 'Quinta', 'Corinthians', 'Racing', TRUE, 'MANDANTE', 'Sulamericana', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Superior', '[618] E-15 [I]', 67.5, 2, 2, 'E', FALSE, FALSE),
    ('2024-11-24', 'Domingo', 'Corinthians', 'Vasco', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[423] K-20 [N]', 112.5, 3, 1, 'V', FALSE, FALSE),
    ('2024-12-03', 'Terça', 'Corinthians', 'Bahia', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[420] JJ-24 [H]', 112.5, 3, 0, 'V', FALSE, FALSE),
    ('2025-01-19', 'Domingo', 'Corinthians', 'Velo Clube', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[421] DD-7 [H]', 118.0, 2, 1, 'V', FALSE, FALSE),
    ('2025-01-22', 'Quarta', 'Corinthians', 'Água Santa', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'AUSENTE', 'Leste Inferior', '[419] CC-26 [H]', 83.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2025-02-09', 'Domingo', 'Corinthians', 'São Bernardo', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] S-21 [N]', 83.0, 2, 0, 'V', FALSE, FALSE),
    ('2025-02-12', 'Quarta', 'Corinthians', 'Santos', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[423] Q-5 [N]', 128.0, 2, 1, 'V', TRUE, FALSE),
    ('2025-02-26', 'Quarta', 'Corinthians', 'U. Central [VEN]', TRUE, 'MANDANTE', 'Libertadores', 'M', 'Neo Química Arena', 'PRESENTE', 'Oeste Superior', '[909] A-24 [B]', NULL, 3, 2, 'V', FALSE, FALSE),
    ('2025-03-02', 'Domingo', 'Corinthians', 'Mirassol', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'AUSENTE', 'Leste Inferior', '[422] U-19 [H]', 128.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2025-03-09', 'Domingo', 'Corinthians', 'Santos', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[422] BB-25 [H]', 138.0, 2, 1, 'V', TRUE, FALSE),
    ('2025-03-12', 'Quarta', 'Corinthians', 'Barcelona SC', TRUE, 'MANDANTE', 'Libertadores', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[423] Q-23 [N]', 128.0, 2, 0, 'V', FALSE, FALSE),
    ('2025-03-27', 'Quinta', 'Corinthians', 'Palmeiras', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[423] C-13 [N]', 158.0, 0, 0, 'E', TRUE, FALSE),
    ('2025-04-05', 'Sábado', 'Corinthians', 'Vasco', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] R-16 [N]', 88.0, 3, 0, 'V', FALSE, FALSE),
    ('2025-04-16', 'Quarta', 'Corinthians', 'Fluminense', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'AUSENTE', 'Leste Superior', '[624] D-13 [L]', 78.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2025-04-19', 'Sábado', 'Corinthians', 'Sport', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'AUSENTE', 'Leste Superior', '[624] N-15 [L]', 78.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2025-05-03', 'Sábado', 'Corinthians', 'Internacional', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[419] JJ-12 [H]', 88.0, 4, 2, 'V', FALSE, FALSE),
    ('2025-07-13', 'Domingo', 'Corinthians', 'Bragantino', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Sul', '[413] AA-20 [E]', 35.0, 1, 2, 'D', FALSE, FALSE),
    ('2025-07-23', 'Quarta', 'Corinthians', 'Cruzeiro', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Norte', 'Gaviões', 35.0, 0, 0, 'E', FALSE, FALSE),
    ('2025-07-30', 'Quarta', 'Corinthians', 'Palmeiras', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[426] R-6 [N]', 88.0, 1, 0, 'V', TRUE, FALSE),
    ('2025-08-03', 'Domingo', 'Corinthians', 'Fortaleza', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'AUSENTE', 'Sul', '[412] C-12 [E]', 35.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2025-08-16', 'Sábado', 'Corinthians', 'Bahia', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Norte', 'Gaviões', 35.0, 1, 2, 'D', FALSE, FALSE),
    ('2025-10-18', 'Sábado', 'Corinthians', 'Atlético-MG', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Norte', 'Gaviões', 35.0, 1, 0, 'V', FALSE, FALSE),
    ('2025-11-20', 'Quinta', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] T-11 [N]', 93.0, 3, 1, 'V', TRUE, FALSE),
    ('2025-12-14', 'Domingo', 'Corinthians', 'Cruzeiro', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] T-10 [N]', 88.0, 1, 2, 'D', FALSE, TRUE),
    ('2025-12-17', 'Quarta', 'Corinthians', 'Vasco', TRUE, 'MANDANTE', 'Copa do Brasil', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] T-10 [N]', 88.0, 0, 0, 'E', FALSE, FALSE),
    ('2025-12-21', 'Domingo', 'Vasco', 'Corinthians', TRUE, 'VISITANTE', 'Copa do Brasil', 'M', 'Maracanã', 'PRESENTE', 'Visitante', 'Gaviões', 300.0, 2, 1, 'V', FALSE, FALSE),
    ('2026-01-11', 'Domingo', 'Corinthians', 'Ponte Preta', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Sul', '[412] C-13 [E]', 35.0, 3, 0, 'V', FALSE, FALSE),
    ('2026-01-18', 'Domingo', 'Corinthians', 'São Paulo', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Sul', '[412] R-11 [E]', 35.0, 1, 1, 'E', TRUE, FALSE),
    ('2026-01-28', 'Quarta', 'Corinthians', 'Bahia', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Vila Belmiro', 'AUSENTE', 'Cadeira Lateral Térrea', '[15] G-153 [26]', 0.0, NULL, NULL, NULL, FALSE, FALSE),
    ('2026-02-05', 'Quinta', 'Corinthians', 'Capivariano', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] T-10 [N]', 79.0, 3, 0, 'V', FALSE, FALSE),
    ('2026-02-08', 'Domingo', 'Corinthians', 'Palmeiras', TRUE, 'MANDANTE', 'Paulista', 'M', 'Neo Química Arena', 'PRESENTE', 'Leste Inferior', '[425] T-10 [N]', 105.0, 0, 1, 'D', TRUE, FALSE),
    ('2026-02-12', 'Quinta', 'Corinthians', 'Bragantino', TRUE, 'MANDANTE', 'Brasileiro', 'M', 'Neo Química Arena', 'AUSENTE', 'Sul', '[] - []', 36.0, NULL, NULL, NULL, FALSE, FALSE);

-- Verificação
SELECT COUNT(*) AS total_jogos FROM jogos;